In [3]:
import pandas as pd

C:\Users\tooka\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\tooka\anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Users\tooka\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

# Read Input xlsx files

In [9]:
df_conversation = pd.read_excel("./data/japanese_persona_chat.xlsx", sheet_name="対話")
df_conversation

         No  ペルソナID 話者                                                 発話
0         1     PP1  A                                      こんにちは。お元気ですか？
1         1     PP1  B                          はい、元気です。広告代理店での仕事が忙しいですが。
2         1     PP1  A                             お疲れさまです。私は介護福祉士をしています。
3         1     PP1  B                  介護福祉士として働いていらっしゃるんですね。大変なお仕事ですよね。
4         1     PP1  A              いえ。広告代理店も大変ですよね。ちなみに私は北海道の一軒家に住んでいます。
...     ...     ... ..                                                ...
61788  5000  PP5000  B              ファッション業界にはろくな男性いなくって！残念ながら恋人はいないのよねー。
61789  5000  PP5000  A            そうなんだ。なかなかうまくいかないものだね。生まれ故郷の北海道に帰ろうかなあ。
61790  5000  PP5000  B  帰りたくて帰るのならいいけど、うまくいかないから帰るなら止めるべきね！それより東京に来たらい...
61791  5000  PP5000  A                                あなたってポジティブだね。見習いたよ。
61792  5000  PP5000  B                            まあね、だてに厳しい業界で揉まれてないからね。

[61793 rows x 4 columns]

In [5]:
df_persona = pd.read_excel("./data/japanese_persona_chat.xlsx", sheet_name="ペルソナリスト")
df_persona

,No,ペルソナID,A,B
0,1,PP1,私は北海道で生まれました。\n私は東京に住んでみたいです。\n私は一軒家に住んでいます。\n...,私は青森で生まれました。\n私は山のそばに住んでいます。\n私は昭和生まれです。\n私は広告...
1,2,PP2,私は青森で生まれました。\n私は山のそばに住んでいます。\n私は昭和生まれです。\n私は広告...,私は以前、沖縄に住んでいたことがあります。\n私は海のそばに住んでいます。\n私はダンスが得...
2,3,PP3,私は以前、沖縄に住んでいたことがあります。\n私は海のそばに住んでいます。\n私はダンスが得...,私は外国生まれです。\n私が生まれたのは冬です。\n私の誕生日は、正月です。\n私は彫りの深...
3,4,PP4,私は外国生まれです。\n私が生まれたのは冬です。\n私の誕生日は、正月です。\n私は彫りの深...,私は秋田で生まれました。\n私は学校のそばに住んでいます。\n私は70年代の生まれです。\n...
4,5,PP5,私は秋田で生まれました。\n私は学校のそばに住んでいます。\n私は70年代の生まれです。\n...,私は新潟から出たことがありません。\n私は実家暮らしです。\n私は整体師です。\n私は足が短...
...,...,...,...,...
4995,4996,PP4996,私は自営業です。\n私は探偵です。\n私は犬を飼っています。\n私は片付けが苦手です。\n私...,私は家政婦です。\n私は姉と暮らしています。\n私のペットはウサギです。\n私が尊敬する人は...
4996,4997,PP4997,私には友だちがたくさんいます。\n私は10代です。\n私はメイクアップアーティストになりたい...,私は自営業です。\n私は探偵です。\n私は犬を飼っています。\n私は片付けが苦手です。\n私...
4997,4998,PP4998,私は4月生まれです。\n私の誕生日は、エイプリルフールです。\n私は自衛隊員です。\n私は責...,私には友だちがたくさんいます。\n私は10代です。\n私はメイクアップアーティストになりたい...
4998,4999,PP4999,私は一人暮らしです。\n私は、センスが良いと人からよく言われます。\n私はスタイリストです。...,私は4月生まれです。\n私の誕生日は、エイプリルフールです。\n私は自衛隊員です。\n私は責...
4999,5000,PP5000,私は北海道で生まれました。\n私は東京に住んでみたいです。\n私は一軒家に住んでいます。\n...,私は一人暮らしです。\n私は、センスが良いと人からよく言われます。\n私はスタイリストです。...

In [89]:
df_user[0:1]["発話"].values[0]

'こんにちは。どっかに素敵な男性との出会いは転がってないかな？'

In [112]:
df_groupby = df_conversation.groupby(["No","ペルソナID"])
df_outputA = pd.DataFrame(columns=["ペルソナID","A1","B1","A2"])
for i in range(1, df_conversation["No"].max()+1):
    df_user = df_groupby.get_group((i,f"PP{i}"))
    for j in range(0,len(df_user)-2,2):
        df_outputA = df_outputA.append(
            {
                "ペルソナID":f"PP{i}",
                "A1":df_user[j:j+1]["発話"].values[0],
                "B1":df_user[j+1:j+2]["発話"].values[0],
                "A2":df_user[j+2:j+3]["発話"].values[0]
            },
            ignore_index=True
        )
df_outputA

,ペルソナID,A1,B1,A2
0,PP1,こんにちは。お元気ですか？,はい、元気です。広告代理店での仕事が忙しいですが。,お疲れさまです。私は介護福祉士をしています。
1,PP1,お疲れさまです。私は介護福祉士をしています。,介護福祉士として働いていらっしゃるんですね。大変なお仕事ですよね。,いえ。広告代理店も大変ですよね。ちなみに私は北海道の一軒家に住んでいます。
2,PP1,いえ。広告代理店も大変ですよね。ちなみに私は北海道の一軒家に住んでいます。,北海道ですか。ご飯の美味しいところで羨ましいです。私は青森県出身で山の多いところが好きなので...,北海道は、美味しいもの多いですよ。青森なら、お近くでしたね。でも、私はいつか東京に住んでみた...
3,PP1,北海道は、美味しいもの多いですよ。青森なら、お近くでしたね。でも、私はいつか東京に住んでみた...,東京ですか。東京には華やかな場所が多いですよね,田舎生まれの私にとって、とても魅力的な場所です。
4,PP1,田舎生まれの私にとって、とても魅力的な場所です。,私にとっても東京は魅力的な場所ですね。お休みの日は何をされていますか？私は写真が趣味です。,私は彼氏いない歴も長くて、休みの日はひとりでのんびりしています。写真、いいですね。
...,...,...,...,...
26509,PP5000,こんにちは。どっかに素敵な男性との出会いは転がってないかな？,こんにちは。待ってても素敵な出会いはやってこない。外へ出て目を光らせなきゃ！,そうだよね。東京に行きたいなあ。東京に住んだら出会いのチャンスが増えそうな気がする！あなたは...
26510,PP5000,そうだよね。東京に行きたいなあ。東京に住んだら出会いのチャンスが増えそうな気がする！あなたは...,わたしは実は東京住み！ファッションのお仕事がしたくって上京したよー。,東京に住んでるんだ、いいなあ。わたしも上京したくなってきた！介護福祉士の仕事なら、東京でも見...
26511,PP5000,東京に住んでるんだ、いいなあ。わたしも上京したくなってきた！介護福祉士の仕事なら、東京でも見...,そんな立派な資格あるならどこでもやっていけるよ！素敵な男性は、うーん、東京でも難しいんだけど。,わたしが今、一軒家に住んでるから、東京でも一軒家に住みたいんだよね。住まいの趣味が合う男性と...
26512,PP5000,わたしが今、一軒家に住んでるから、東京でも一軒家に住みたいんだよね。住まいの趣味が合う男性と...,ファッション業界にはろくな男性いなくって！残念ながら恋人はいないのよねー。,そうなんだ。なかなかうまくいかないものだね。生まれ故郷の北海道に帰ろうかなあ。
26513,PP5000,そうなんだ。なかなかうまくいかないものだね。生まれ故郷の北海道に帰ろうかなあ。,帰りたくて帰るのならいいけど、うまくいかないから帰るなら止めるべきね！それより東京に来たらい...,あなたってポジティブだね。見習いたよ。

In [117]:
df_groupby = df_conversation.groupby(["No","ペルソナID"])
df_outputB = pd.DataFrame(columns=["ペルソナID","A1","B1","A2"])
for i in range(1, df_conversation["No"].max()+1):
    df_user = df_groupby.get_group((i,f"PP{i}"))
    for j in range(0,len(df_user)-3,2):
        df_outputB = df_outputB.append(
            {
                "ペルソナID":f"PP{i}",
                "B1":df_user[j+1:j+2]["発話"].values[0],
                "A1":df_user[j+2:j+3]["発話"].values[0],
                "B2":df_user[j+3:j+4]["発話"].values[0]
            },
            ignore_index=True
        )
df_outputB

,ペルソナID,A1,B1,A2,B2
0,PP1,お疲れさまです。私は介護福祉士をしています。,はい、元気です。広告代理店での仕事が忙しいですが。,NaN,介護福祉士として働いていらっしゃるんですね。大変なお仕事ですよね。
1,PP1,いえ。広告代理店も大変ですよね。ちなみに私は北海道の一軒家に住んでいます。,介護福祉士として働いていらっしゃるんですね。大変なお仕事ですよね。,NaN,北海道ですか。ご飯の美味しいところで羨ましいです。私は青森県出身で山の多いところが好きなので...
2,PP1,北海道は、美味しいもの多いですよ。青森なら、お近くでしたね。でも、私はいつか東京に住んでみた...,北海道ですか。ご飯の美味しいところで羨ましいです。私は青森県出身で山の多いところが好きなので...,NaN,東京ですか。東京には華やかな場所が多いですよね
3,PP1,田舎生まれの私にとって、とても魅力的な場所です。,東京ですか。東京には華やかな場所が多いですよね,NaN,私にとっても東京は魅力的な場所ですね。お休みの日は何をされていますか？私は写真が趣味です。
4,PP1,私は彼氏いない歴も長くて、休みの日はひとりでのんびりしています。写真、いいですね。,私にとっても東京は魅力的な場所ですね。お休みの日は何をされていますか？私は写真が趣味です。,NaN,1人でのんびりと過ごす時間も大切で、贅沢なものですよ。私もよく家でのんびり過ごしています。
...,...,...,...,...,...
25274,PP5000,そうだよね。東京に行きたいなあ。東京に住んだら出会いのチャンスが増えそうな気がする！あなたは...,こんにちは。待ってても素敵な出会いはやってこない。外へ出て目を光らせなきゃ！,NaN,わたしは実は東京住み！ファッションのお仕事がしたくって上京したよー。
25275,PP5000,東京に住んでるんだ、いいなあ。わたしも上京したくなってきた！介護福祉士の仕事なら、東京でも見...,わたしは実は東京住み！ファッションのお仕事がしたくって上京したよー。,NaN,そんな立派な資格あるならどこでもやっていけるよ！素敵な男性は、うーん、東京でも難しいんだけど。
25276,PP5000,わたしが今、一軒家に住んでるから、東京でも一軒家に住みたいんだよね。住まいの趣味が合う男性と...,そんな立派な資格あるならどこでもやっていけるよ！素敵な男性は、うーん、東京でも難しいんだけど。,NaN,ファッション業界にはろくな男性いなくって！残念ながら恋人はいないのよねー。
25277,PP5000,そうなんだ。なかなかうまくいかないものだね。生まれ故郷の北海道に帰ろうかなあ。,ファッション業界にはろくな男性いなくって！残念ながら恋人はいないのよねー。,NaN,帰りたくて帰るのならいいけど、うまくいかないから帰るなら止めるべきね！それより東京に来たらい...
25278,PP5000,あなたってポジティブだね。見習いたよ。,帰りたくて帰るのならいいけど、うまくいかないから帰るなら止めるべきね！それより東京に来たらい...,NaN,まあね、だてに厳しい業界で揉まれてないからね。

# Output to text file

In [118]:
with open("./j_perchat.txt", mode="w", encoding="utf-8") as f:
    for pid in df_persona["ペルソナID"].unique().tolist():
        i = 1
        # ペルソナの書き出し
        for persona in df_persona[df_persona["ペルソナID"]==pid]["A"].values[0].split("\n"):
            f.write(f"{i} your persona: {persona}\n")
            i+=1
        # 対話ペアの書き出し
        for index, row in df_outputA[df_outputA["ペルソナID"]==pid].iterrows():
            f.write(f'{i} {row["A1"]}\t{row["B1"]}\t{row["A2"]}\n')
            i+=1
        i = 1
        # ペルソナの書き出し
        for persona in df_persona[df_persona["ペルソナID"]==pid]["B"].values[0].split("\n"):
            f.write(f"{i} your persona: {persona}\n")
            i+=1
        # 対話ペアの書き出し
        for index, row in df_outputB[df_outputB["ペルソナID"]==pid].iterrows():
            f.write(f'{i} {row["B1"]}\t{row["A1"]}\t{row["B2"]}\n')
            i+=1

# Convert .ipynb to .py

In [119]:
import subprocess
subprocess.run(['jupyter', 'nbconvert', '--to', 'script', '*.ipynb'])

CompletedProcess(args=['jupyter', 'nbconvert', '--to', 'script', '*.ipynb'], returncode=0)